FROM golang:1.23.4-alpine AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOOS linux

RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

ADD go.mod .
ADD go.sum .

RUN go mod download

COPY . .

RUN go build -ldflags="-s -w" -o /app/main ./cmd/api/main.go

FROM alpine:3.17 AS worker

WORKDIR /app

COPY --from=builder /app/main /app/main
COPY --from=builder /build/.env /app/.env

RUN chmod +x /app/main

CMD ["/app/main"]